# Generated by Django 4.1.5 on 2023-01-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=150, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('country', models.CharField(max_length=150, verbose_name='Производитель')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='TypeDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип привода')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Приввод',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(blank=True, default=True, max_length=4, verbose_name='Год')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/%Y/%m/%d', verbose_name='Фото')),
                ('speed', models.PositiveSmallIntegerField(blank=True, default=True, max_length=3, verbose_name='Скорость')),
                ('control', models.PositiveSmallIntegerField(blank=True, default=True, max_length=3, verbose_name='Управление')),
                ('acceleration', models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Ускорение')),
                ('start', models.PositiveSmallIntegerField(blank=True, default=True, max_length=3, verbose_name='Старт')),
                ('brake', models.PositiveSmallIntegerField(blank=True, default=True, max_length=3, verbose_name='Торможение')),
                ('Hp', models.PositiveSmallIntegerField(blank=True, default=True, max_length=3, verbose_name='Л.с.')),
                ('Hm', models.PositiveSmallIntegerField(blank=True, default=True, max_length=3, verbose_name='Н/м')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=True, max_length=4, verbose_name='Вес')),
                ('level', models.PositiveSmallIntegerField(blank=True, default=True, max_length=4, verbose_name='Класс')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.brands', verbose_name='Бренд')),
                ('type_drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.typedrive', verbose_name='Тип привода')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['year'],
            },
        ),
    ]
