# Generated by Django 4.1.5 on 2023-01-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Hm',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Н/м'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Hp',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Л.с.'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='brake',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Торможение'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='control',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='speed',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='start',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Старт'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Год'),
        ),
    ]
