# Generated by Django 4.1.5 on 2023-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_cars_hm_alter_cars_hp_alter_cars_brake_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['brand'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=True, verbose_name='Цена'),
        ),
    ]
