# Generated by Django 4.1.5 on 2023-01-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_cars_options_cars_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['model'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
